### ISSUE TITLE
Filter panel text truncation broken in Chrome

### ISSUE THREAD

**Issue by RNCTX** [The-Politico/django-kanban-budget#35]
On the pop out right-hand filter panel when looking at a board (where you filter by "Dev" or date range) the text-overflow is set to ellipsis.  This doesn't work properly in the current Chrome unless the base overflow property is set to hidden.

Before:

![screen shot 2018-06-10 at 9 02 32 pm](https://user-images.githubusercontent.com/13775820/41209665-8752535c-6cf2-11e8-8e11-8d70f7804a5c.png)

After:

![screen shot 2018-06-10 at 9 02 54 pm](https://user-images.githubusercontent.com/13775820/41209669-8d4e57a6-6cf2-11e8-8a00-f5b3758c46cf.png)

Fixed in the linked PR.

**Comment by hobbes7878** [comment]
PR accepted. Will roll in a release this week.
