### ISSUE TITLE
Add important info to README

### ISSUE THREAD

**Issue by m-thielen** [The-Politico/django-kanban-budget#37]
If django-kanban-budget is deployed using Apache and mod_wsgi, you have to set

`WSGIPassAuthorization On`

in the Apache config. Otherwise all REST calls fail. The error in the JavaScript console is totally misleading, so this problem is hard to trace down.

You should add this info to your README, I think.

**Comment by hobbes7878** [comment]
Thanks, @m-thielen.

I probably won't add that to the docs of this project because it's deployment-specific config outside the scope of Django.
